---
title: "Trends in Cryptocurrency"
author: "Chintan Nayak"
date: "01/12/2021"
output: html_document
---

```{r}
library(tidyverse)
library(dplyr)
library(lubridate)
require (ggplot2)

my_theme = theme(panel.grid = element_line(color = '#e6e6e6'),
                 panel.background = element_rect(fill = 'white'),
                 plot.title = element_text(hjust = .5, size = 18, colour = '#ffa500'),
                 text = element_text(family = 'Georgia'),
                 axis.text = element_text(size = 6),
                 axis.title = element_text(size = 18, family = 'Georgia', face = 'bold'),
                 axis.line = element_line(colour = '#737373', size = 1),
                 strip.background = element_rect(colour = "blue", fill = "white"),
                 strip.text = element_text(face = 'bold'))

Project_data <- read_csv("/Users/HP/Documents/Project_data.csv")
Project_data_hr <- read_csv("/Users/HP/Documents/Project_data_hr.csv")
```

```{r}
ProjectDt= Project_data %>%
  mutate(Date = dmy(Date)) %>%
  mutate(Vol. = case_when(
    endsWith(Vol., "K") ~ as.numeric(str_sub(Vol., end = -2))*1000,
    endsWith(Vol., "M") ~ as.numeric(str_sub(Vol., end = -2))*100000,
    endsWith(Vol., "B") ~ as.numeric(str_sub(Vol., end = -2))*10000000))%>%
  mutate(ChangeP = as.numeric(str_sub(ChangeP, end = -2)))%>%
  mutate(Volatality= High-Low)%>%
  mutate(VolatalityP=((High-Low)*100)/High)%>%
  group_by(Crypto)

ProjectDt

```


```{r}
ProDelta=Project_data_hr%>%
  mutate(Date = mdy(Date)) %>%
  mutate(DateTime= (ymd(Date) + hms(Time)))%>%
  mutate(Volatality= High-Low)%>%
  mutate(VolatalityP=((High-Low)*100)/High)%>%
  group_by(Crypto)

ProDelta
```


```{r}
Fullrange= ProjectDt%>%
  filter(Date >= as.Date("2021-05-05") & Date <= as.Date("2021-05-20"))

```

```{r}
Event1= ProDelta %>%
  filter(Date >= as.Date("2021-05-12") & Date <= as.Date("2021-05-13"))

```

```{r}
Event2= ProDelta %>%
  filter(Date >= as.Date("2021-05-19") & Date <= as.Date("2021-05-20"))

```


```{r}
ggplot(Fullrange, aes(Date, ChangeP)) + geom_line() + facet_wrap(~ Crypto) +
  labs(title = '5th May 2021- 20th May 2021, Price Analysis') +
scale_y_continuous(breaks = c(-35, -30, -25, -20, -15, -10, -5, 0, 5, 10, 15, 20), 
                     labels = c('-35', '-30','-25', '-20', '-15', '-10', '-5', '0', '5', '10', '15', '20')) + 
scale_x_date(breaks = as.Date(c("2021-05-05", "2021-05-06","2021-05-07","2021-05-08","2021-05-09","2021-05-10","2021-05-11","2021-05-12","2021-05-13","2021-05-14","2021-05-15","2021-05-16","2021-05-17","2021-05-18","2021-05-19","2021-05-20")), labels=c('5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20')) + my_theme
```
```{r}

ggplot(Event1, aes(DateTime, ChangeP, color= Crypto)) + geom_line() +
  scale_x_datetime(breaks = as_datetime(c("2021-05-12 06:00:00", "2021-05-12 12:00:00", "2021-05-12 18:00:00", "2021-05-13 00:00:00", "2021-05-13 06:00:00", "2021-05-13 12:00:00", "2021-05-13 18:00:00" )), labels=c('12-06', '12-14', '12-18', '13-00', '13-06', '13-12', '13-18')) +
  labs(title = 'Elon Musk Tweet Effect on Price')  +
  scale_y_continuous(breaks = c(-10, -7.5, -5, -2.5, 0, 2.5, 5, 7.5, 10), 
                     labels = c('-10', '-7.5', '-5', '-2.5', '0', '2.5', '5', '7.5', '10')) + my_theme
```

```{r}
ggplot(Event2, aes(DateTime, ChangeP, color= Crypto)) + geom_point() +
  scale_x_datetime(breaks = as_datetime(c("2021-05-19 06:00:00", "2021-05-19 12:00:00", "2021-05-19
                                          18:00:00", "2021-05-20 00:00:00", "2021-05-20 06:00:00", "2021-05-20 12:00:00", "2021-05-20 18:00:00" )), labels=c('19-06', '19-14', '19-18', '20-00', '20-06', '20-12', '20-18')) +
  labs(title = 'China curbs on cryptocurrency Effect on Price')  +
  scale_y_continuous(breaks = c(-15, -12.5, -10, -7.5, -5, -2.5, 0, 2.5, 5, 7.5, 10), 
                     labels = c('-15', '-12.25','-10', '-7.5', '-5', '-2.5', '0', '2.5', '5', '7.5', '10')) + my_theme
```



```{r}
ggplot(Fullrange, aes(Date, Vol.)) + geom_line() + facet_grid(~ Crypto) +
  labs(title = '5th May 2021- 20th May 2021, Volume Analysis') +
  scale_x_date(breaks = as.Date(c("2021-05-05", "2021-05-06","2021-05-07","2021-05-08","2021-05-09","2021-05-10","2021-05-11","2021-05-12","2021-05-13","2021-05-14","2021-05-15","2021-05-16","2021-05-17","2021-05-18","2021-05-19","2021-05-20")), labels=c('5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20'))+
  my_theme
```
```{r}
ggplot(Event1, aes(DateTime, ChangeV, color= Crypto)) + geom_point()  +
  labs(title = 'Elon Musk Tweet Effect on Volume') + 
  scale_x_datetime(breaks = as_datetime(c("2021-05-12 06:00:00", "2021-05-12 12:00:00", "2021-05-12 18:00:00", "2021-05-13 00:00:00", "2021-05-13 06:00:00", "2021-05-13 12:00:00", "2021-05-13 18:00:00" )), labels=c('12-06', '12-14', '12-18', '13-00', '13-06', '13-12', '13-18')) +
  scale_y_continuous(breaks = c(-100, -50 , 0, 50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600), 
                     labels = c('-100','-50', '0', '50', '100', '150', '200', '250', '300', '350', '400', '450', '500', '550','600')) + my_theme
```

```{r}
ggplot(Event2, aes(DateTime, ChangeV, color = Crypto)) + geom_point()  +
  labs(title = 'China curbs on cryptocurrency Effect on Volume') + scale_x_datetime(breaks = as_datetime(c("2021-05-19 06:00:00", "2021-05-19 12:00:00", "2021-05-19
                                          18:00:00", "2021-05-20 00:00:00", "2021-05-20 06:00:00", "2021-05-20 12:00:00", "2021-05-20 18:00:00" )), labels=c('19-06', '19-14', '19-18', '20-00', '20-06', '20-12', '20-18')) +
  scale_y_continuous(breaks = c(-100, -50 , 0, 50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600), 
                     labels = c('-100','-50', '0', '50', '100', '150', '200', '250', '300', '350', '400', '450', '500', '550','600')) + my_theme
```


```{r}
ggplot(Fullrange, aes(Date, VolatalityP)) + geom_line() + facet_wrap(~ Crypto) +
  labs(title = '5th May 2021- 20th May 2021, Volatality Analysis') +
scale_y_continuous(breaks = c(0, 10, 20, 30, 40, 50), 
                     labels = c('0', '10', '20', '30', '40', '50')) + 
scale_x_date(breaks = as.Date(c("2021-05-05", "2021-05-06","2021-05-07","2021-05-08","2021-05-09","2021-05-10","2021-05-11","2021-05-12","2021-05-13","2021-05-14","2021-05-15","2021-05-16","2021-05-17","2021-05-18","2021-05-19","2021-05-20")),labels=c('5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20')) + my_theme
```

```{r}

ggplot(Event1, aes(DateTime, VolatalityP, color= Crypto)) + geom_line() +
  labs(title = 'Elon Musk Tweet Effect on Volatality') +
  scale_x_datetime(breaks = as_datetime(c("2021-05-12 08:00:00", "2021-05-12 14:00:00", "2021-05-12 20:00:00", "2021-05-13 02:00:00", "2021-05-13 08:00:00", "2021-05-13 14:00:00", "2021-05-13 20:00:00" )), labels=c('12-08', '12-14', '12-20', '13-02', '13-08', '13-14', '13-20')) +
  scale_y_continuous(breaks = c(0, 2.5, 5, 7.5, 10, 12.5, 15), 
                     labels = c('0', '2.5', '5', '7.5', '10', '12.5', '15')) + my_theme
```

```{r}
ggplot(Event2, aes(DateTime, VolatalityP, color= Crypto)) + geom_point() +
  labs(title = 'China curbs on cryptocurrency Effect on Volatility') + scale_x_datetime(breaks = as_datetime(c("2021-05-19 06:00:00", "2021-05-19 12:00:00", "2021-05-19 18:00:00", "2021-05-20 00:00:00", "2021-05-20 06:00:00", "2021-05-20 12:00:00", "2021-05-20 18:00:00" )), labels=c('19-06', '19-14', '19-18', '20-00', '20-06', '20-12', '20-18')) + 
  scale_y_continuous(breaks = c(0, 5, 10, 15, 20, 25, 30, 35, 40), 
                     labels = c('0', '5', '10', '15', '20', '25', '30', '35', '40')) + my_theme
```

